export const ingredients = [
  {
    imagePath: "assets/images/ingredients/lpg-organicCondiitoner.jpg",
    title: "Organic Detox Shampoo",
    subtitle: "Restore natural shine and volume with our shampoo that is for all hair types",
    description: "The perfect Detox Shampoo. Have you ever felt that your hair gets dirty quickly after washing? Then we have the answer. Thanks to natural ingredients such as thistle and yuzu stem cell extracts, this shampoo gives you a detoxifying treatment. The product is free of silicones, parabens, SLS and SLES which otherwise contribute to dry scalp and thus increase fat in the scalp. That is why it can take about 2-4 weeks for your hair to get used to this healthy habit. But do not worry - after these weeks, your hair will be cleaner longer between washes. Safe to use on even colored and curly hair. The shampoo contains hydrolyzed quinoa extract which protects and preserves even colored hair.",
    subdescription: "<b>Good to know</b><br/>Suitable for all hair types.<br/>Apply on wet hair, massage in and rinse off",
    list: "Aqua (water), Citrus Junos Fruit Extract (Yuzu extract – helps keeping hair strong), Silybum Marianum Callus Extract (Thistle stem cell extract – helps fight skin irritation and cell renewal), Cocamidopropyl Betaine (naturally derived surfactant sourced from coconut), Hydrogenated Olive Oil Unsaponifiables (Conditioning agent derived from olive oil), Caprylyl/Capryl Glucoside (mild cleansing agent derived from raw vegetable materials), Glycerin (natural moisturizer from sourced from plant oils), Citrus Grandis Peel Oil (Natural grapefruit extract), Sodium PCA (natural conditioning agent derived from amino acids), Sodium Anisate (A 100% natural preservative derived from anise and fennel), Sodium Levulinate (A 100% natural preservative derived from starch and vegetal inulin), Hydrolyzed Quinoa (Natural quinoa protein – adding strength and protects the hair), Sodium Cocoyl Glutamate (Natural cleansing agent extracted from coconut oil), Crambe Abyssinica Seed Oil Phytosterol Esters (Abyssinian seed oil – adding moisture and shine to hair), Polyglyceryl-6 Oleate (natural emulsifier, ester from oleic acid), Hydrogenated Ethylhexyl Olivate (natural replacement for synthetic silicone. Mildly made from olive oil – has antistatic and heat protection effect), Citrus Sinensis Peel Oil Expressed (Grapefruit extract), PCA Ethyl Cocoyl Arginate (Anti-static agent derived from plant sourced amino acids), Glyceryl Caprylate (Conditioning & emulsifying agent sourced from various vegetable oils), Sodium Phytate (natural chelating agent derived from plants), Citric Acid (Natural pH regulator derived from kassavaroot), Sodium Lauroyl Glutamate (Mild amino acid based surfactant), Sodium Benzoate (preservative), Sodium Surfactin (cleansing agent – a peptidelipid composed of amino acids and fatty acids), Maltodextrin (Conditioning agent from natural starch), Sodium Lauryl Sulfoacetate (naturally derived surfactant sourced from coconut), Sodium Lauroyl Sarcosinate (natural cleanser/foam booster derived sourced from coconut oil), Alcohol (from Sodium Phytate), Parfum (from organic essential oils), Limonene (naturally found in essential oils)"
  },{
    imagePath: "assets/images/ingredients/lpg-organicCondiitoner.jpg",
    title: "Organic Detox Conditioner",
    subtitle: "Moisturize your tops properly with our moisturizing conditioner.",
    description: "A rich and moisturizing conditioner formulated with natural ingredients such as argan oil, grapefruit extract and shea butter. The conditioner is rich in antioxidants and vitamin C which protects and boosts the hair with extra shine. Leaves hair soft, smooth and easy to brush through. Safe to use on colored and curly hair.",
    subdescription: "<b>Good to know</b><br/>Apply in the tops and wait 2-3 minutes before rinsing out the product. Do you want to use the conditioner as a hair wrap for an extra moisture boost? Massage the conditioner into the entire hair and let sit for 20 minutes before rinsing.",
    list: "Aqua (water), Citrus Junos Fruit Extract (Yuzu extract – helps keeping hair strong), Silybum Marianum Callus Extract (Thistle stem cell extract – helps fight skin irritation and cell renewal), Hydrolyzed Quinoa (Natural quinoa protein - adding strength and protects the hair), Cetearyl Alcohol (natural emulsifier derived from vegetable oils), Behenamidopropyl Dimethylamine (Antistatic agent from rapeseed oil), Glycerin (natural moisturizer from sourced from plant oils), Citrus Grandis Peel Oil (Grapefruit extract), Argania Spinosa Kernel Oil (argan oil – moisturizes the hair), Butyrospermum Parkii Butter (shea butter – moisturizes the hair), Crambe Abyssinica Seed Oil Phytosterol Esters (Abyssinian seed oil - adding moisture and shine to hair), Lactic Acid (natural skin conditioning agent), Sodium Anisate (A 100% natural preservative derived from anise and fennel), Sodium Levulinate (A 100% natural preservative derived from starch and vegetal inulin), Citrus Sinensis Peel Oil Expressed (orange extract), Hydrolyzed Rice Protein (Conditioning agent from non-GMO rice protein – adding volume and shine to hair), Sodium Benzoate (preservative), Benzyl Alcohol (naturally found in essential oils), Maltodextrin (Conditioning agent from natural starch), Potassium Sorbate (natural preservative derived from salt), Parfum (from organic essential oils), Limonene (naturally found in essential oils)"
  }
]